[package]
name = "speer-sys"
version = "0.2.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/jk20342/speer-sys-rust"
homepage = "https://github.com/jk20342/speer-sys-rust"
description = "raw rust ffi bindings for speer"
documentation = "https://docs.rs/speer-sys"
links = "speer"
build = "build.rs"
include = [
    "Cargo.toml",
    "README.md",
    "build.rs",
    "wrapper.h",
    "src/**",
    "vendor/speer/CMakeLists.txt",
    "vendor/speer/LICENSE",
    "vendor/speer/README.md",
    "vendor/speer/speer.pc.in",
    "vendor/speer/cmake/**",
    "vendor/speer/docs/**",
    "vendor/speer/include/**",
    "vendor/speer/src/**",
]

[package.metadata.docs.rs]
features = ["full-chat"]

[features]
default = ["build-from-source"]
build-from-source = ["dep:cmake"]
full-chat = ["libp2p-tcp"]
libp2p-identify = []
libp2p-kad = ["libp2p-tcp", "libp2p-identify"]
libp2p-tcp = []
static = []

[build-dependencies]
bindgen = "0.72"
cmake = { version = "0.1", optional = true }
pkg-config = "0.3"
